# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c35e7d97b9a3cb8a53f3159fcb8038d0a25593629b6ed546a8bcd66132dc3881c9fd703070d8f42502556811752b331c28c13536feb08aca7cb17e01df0e5668

test:
  secret_key_base: ddf489a09848daaf4109cac3bcd13a24c2c55c9d4f5ead24b879e8f2fe53bb8a33b4e9378a94ef06a3b2446d1eecfd3b4ea6c172cb2a009544ad502c5b273974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
